### PR TITLE
Added the Log4Net Logger name to the log properties json.

### PR DESCRIPTION
**Pull request by sheastrickland**

### CODE REVIEW

**Comment by nblumhardt** [comment]
Awesome - I didn't know this was possible!

So that it lines up with other logs in Seq, would it make sense to name the property `SourceContext`?

**Comment by sheastrickland** [comment]
I thought about it, though that Constant is in a separate project, and didn't want to cause any confusion to where it's coming from. Happy to be consistent on that one.

I can just hard code "SourceContext" string in there, if desired.

**Comment by nblumhardt** [comment]
That's a fair point; I'd probably expect it to be called Logger too, come to think of it.

When I run the log4net client here, I get properties prefixed with `log4net_` rather than `log4net:` - it's been a while since I dug into this code, am I missing something?

Cheers!

**Comment by sheastrickland** [comment]
The call to `SanitizeKey("log4net:Logger")` is what encodes the value, I kept the same `log4net:Username` format as log4net uses... we can save some cycles by removing the Sanitize :)

**Comment by nblumhardt** [comment]
Ah I see :-) Thanks Shea!

**Comment by nblumhardt** [comment]
Out in 2.2.5 http://www.nuget.org/packages/seq.client.log4net

**Comment by sheastrickland** [comment]
Awesome, thanks Nick!

**Pull request merged**
